apiVersion: v1
kind: Pod
metadata: 
    name: mssqlgr4transaction
    labels: 
      app: mssqlgr4transaction
      type: database
spec:
    containers:
    - image: mcr.microsoft.com/mssql/server:2019-latest
      name: mssqlgr4transaction
      ports:
      - containerPort: 1433
        protocol: TCP
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "F21swtdisp!!"

---

apiVersion: v1
kind: Service
metadata: 
    name: mssqlgr4transaction-service
spec:
    type: ClusterIP
    ports:
    - targetPort: 1433
      port: 30336
      protocol: TCP
    selector: 
      app: mssqlgr4transaction
      type: database