apiVersion: apps/v1
kind: Deployment
metadata:
    name: grp4transaction
    namespace: swtdisp-gr4
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grp4transaction
            type: transaction-service
    template: 
        metadata: 
            labels: 
                app: grp4transaction
                type: transaction-service
        spec: 
            containers: 
            - name: grp4transaction
              image: pinkrandi/transaction:18
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4transaction-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4transaction
      type: transaction-service