// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserCatalogService.Data;

namespace UserCatalogService.Migrations
{
    [DbContext(typeof(UserCatalogContext))]
    [Migration("20210602150212_changedUsers")]
    partial class changedUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserCatalogService.Model.UserCatalog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Capital")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCatalog");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Capital = 200.09999999999999,
                            Name = "Trang",
                            ShareIds = "123456,162535"
                        },
                        new
                        {
                            Id = "2",
                            Capital = 300.10000000000002,
                            Name = "Mads",
                            ShareIds = "123457,162536"
                        },
                        new
                        {
                            Id = "3",
                            Capital = 400.10000000000002,
                            Name = "Randi",
                            ShareIds = "123458,162537"
                        },
                        new
                        {
                            Id = "4",
                            Capital = 100.09999999999999,
                            Name = "Alexander",
                            ShareIds = "123459,615243"
                        },
                        new
                        {
                            Id = "5",
                            Capital = 50.100000000000001,
                            Name = "Jonas",
                            ShareIds = "123460,615244"
                        },
                        new
                        {
                            Id = "6",
                            Capital = 700.60000000000002,
                            Name = "Thanh",
                            ShareIds = "654321,615245"
                        },
                        new
                        {
                            Id = "7",
                            Capital = 1000.8,
                            Name = "Nikolaj",
                            ShareIds = "654322,615246"
                        },
                        new
                        {
                            Id = "8",
                            Capital = 109.8,
                            Name = "Frank",
                            ShareIds = "654323"
                        },
                        new
                        {
                            Id = "9",
                            Capital = 1650.77,
                            Name = "Poul",
                            ShareIds = "654324"
                        },
                        new
                        {
                            Id = "10",
                            Capital = 980.60000000000002,
                            Name = "Jenny",
                            ShareIds = "162534"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
