// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserCatalogService.Data;

namespace UserCatalogService.Migrations
{
    [DbContext(typeof(UserCatalogContext))]
    [Migration("20210602063407_addSeedData")]
    partial class addSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserCatalogService.Model.UserCatalog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Capital")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCatalog");

                    b.HasData(
                        new
                        {
                            Id = "20",
                            Capital = 100.09999999999999,
                            Name = "Ida Hansen",
                            ShareIds = "12224,12225"
                        },
                        new
                        {
                            Id = "1",
                            Capital = 200.09999999999999,
                            Name = "Trang",
                            ShareIds = "12226,12227"
                        },
                        new
                        {
                            Id = "2",
                            Capital = 300.10000000000002,
                            Name = "Mads",
                            ShareIds = "12228"
                        },
                        new
                        {
                            Id = "3",
                            Capital = 400.10000000000002,
                            Name = "Randi",
                            ShareIds = "12229"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
