apiVersion: apps/v1
kind: Deployment
metadata: 
    name: grp4-tobintaxing
    namespace: swtdisp-gr4
spec: 
    replicas: 1
    selector: 
        matchLabels: 
            app: grp4-tobintaxing
            type: tobintaxing-service
    template: 
        metadata: 
            labels: 
                app: grp4-tobintaxing
                type: tobintaxing-service
        spec:
            containers:
            - name: tobintaxing
              image: mbm92/tobintaxing:v1
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4-tobingtaxing-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4-tobintaxing
      type: tobintaxing-service