apiVersion: apps/v1
kind: Deployment
metadata:
    name: grp4usercatalog
    namespace: swtdisp-gr4
spec:
    replicas: 1
    selector: 
        matchLabels: 
            app: grp4usercatalog
            type: usercatalog-service
    template: 
        metadata: 
            labels: 
                app: grp4usercatalog
                type: usercatalog-service
        spec: 
            containers: 
            - name: usercatalog
              image: macattck/usercatalog:v9
              resources:
                limits:
                    cpu: 200m
                    memory: 128Mi
                requests:
                    cpu: 50m
                    memory: 64Mi
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4usercatalog-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4usercatalog
      type: usercatalog-service