apiVersion: apps/v1
kind: Deployment
metadata:
    name: grp4buyshare
    namespace: swtdisp-gr4
spec:
    replicas: 1
    selector: 
        matchLabels: 
            app: grp4buyshare
            type: buyshare-service
    template: 
        metadata: 
            labels: 
                app: grp4buyshare
                type: buyshare-service
        spec: 
            containers: 
            - name: buyservice
              image: macattck/buyservice:v17
              resources:
                limits:
                    cpu: 200m
                    memory: 128Mi
                requests:
                    cpu: 50m
                    memory: 64Mi
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4buyshare-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4buyshare
      type: buyshare-service