apiVersion: apps/v1
kind: Deployment
metadata:
    name: buyservice
    namespace: swtdisp-gr4
spec:
    replicas: 1
    selector: 
        matchLabels: 
            app: buyservice
            type: backend-microservice
    template: 
        metadata: 
            labels: 
                app: buyservice
                type: backend-microservice
        spec: 
            containers: 
            - name: buyservice
              image: macattck/buyservice:v8
              resources:
                limits:
                    cpu: 200m
                    memory: 128Mi
                requests:
                    cpu: 50m
                    memory: 64Mi
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: buyservice-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: buyservice
      type: backend-microservice