apiVersion: v1
kind: Pod
metadata: 
    name: mssqlgr4-sharecatalog
    namespace: swtdisp-gr4
    labels: 
      app: mssqlgr4-sharecatalog
      type: database
spec:
    containers:
    - image: mcr.microsoft.com/mssql/server:2019-latest
      name: mssqlgr4-sharecatalog
      ports:
      - containerPort: 1433
        protocol: TCP
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "F21swtdisp!!"

---

apiVersion: v1
kind: Service
metadata: 
    name: mssqlgr4-sharecatalog-service
    namespace: swtdisp-gr4
spec:
    type: ClusterIP
    ports:
    - targetPort: 1433
      port: 30567
      protocol: TCP
    selector: 
      app: mssqlgr4-sharecatalog
      type: database