apiVersion: apps/v1
kind: Deployment
metadata: 
    name: grp4-sharecatalog
    namespace: swtdisp-gr4
spec: 
    replicas: 1
    selector: 
        matchLabels: 
            app: grp4-sharecatalog
            type: sharecatalog-service
    template: 
        metadata: 
            labels: 
                app: grp4-sharecatalog
                type: sharecatalog-service
        spec:
            containers:
            - name: sharecatalog
              image: mbm92/shareservice:v7
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4-sharecatalog-service
    namespace: swtdisp-gr4
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4-sharecatalog
      type: sharecatalog-service