apiVersion: apps/v1
kind: Deployment
metadata:
    name: grp4broker
    namespace: swtdisp-gr4
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grp4broker
            type: broker-service
    template: 
        metadata: 
            labels: 
                app: grp4broker
                type: broker-service
        spec: 
            containers: 
            - name: grp4broker
              image: pinkrandi/broker:7
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: grp4broker-service
    namespace: swtdisp-gr4
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
    selector:
      app: grp4broker
      type: broker-service
